### ISSUE TITLE
HD path on > 10000000000 not working, keeps hanging

### ISSUE THREAD

**Issue by user3470** [chatch/stellar-hd-wallet#17]
Deriving path on index greater than 10000000000, package get stuck

**Comment by user3470** [comment]
`this.derive(`m/44'/148'/${index}'`); `

if index is >= 10000000000 it fails any idea why. Please help!

**Comment by chatch** [comment]
@user3470 I just tried this and get an out of range error:
```
> wallet.derive(`m/44'/148'/10000000000'`)
Uncaught:
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 12_147_483_648
    at checkInt (internal/buffer.js:69:11)
    at writeU_Int32BE (internal/buffer.js:799:3)
    at Buffer.writeUInt32BE (internal/buffer.js:812:10)
```

What context are you running this in and what version of nodejs? I'm using node 14.16.1 and running in a repl ...
